
[build]
  publish = "."
  command = "echo 'Static site - no build required'"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = false
  minify = false

[build.processing.js]
  bundle = false
  minify = false

[build.processing.html]
  pretty_urls = false

[build.environment]
  EXCHANGE_RATE_API_KEY = ""

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://pagead2.googlesyndication.com https://api.exchangerate-api.com https://v6.exchangerate-api.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self' https://api.exchangerate-api.com https://v6.exchangerate-api.com; frame-src https://googleads.g.doubleclick.net https://tpc.googlesyndication.com"

[[redirects]]
  from = "/hugo/*"
  to = "/"
  status = 301

[[redirects]]
  from = "/themes/*"
  to = "/"
  status = 301

[context.production.environment]
  EXCHANGE_RATE_API_KEY = ""
